# Generated by Django 3.1.7 on 2021-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210416_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_view_user_list', 'Can view user list')]},
        ),
    ]
