# Generated by Django 3.1.7 on 2021-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='todolist.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=130, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_type', to='todolist.issue', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_issue', to='todolist.type', verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type', through='todolist.IssueType', to='todolist.Type'),
        ),
    ]
