# Generated by Django 3.1.7 on 2021-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210312_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='type_new',
            field=models.ManyToManyField(blank=True, related_name='issue', to='webapp.Type'),
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
