# Generated by Django 3.1.7 on 2021-03-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210312_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type_new',
            new_name='type',
        ),
    ]
