# Generated by Django 3.1.7 on 2021-03-16 12:15

from django.db import migrations, models
import todolist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20210312_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=130, validators=[todolist.validators.SymbolCheckValidator(['%', '$', '@', '#', '^'])], verbose_name='Название'),
        ),
    ]
