# Generated by Django 3.1.7 on 2021-03-17 10:46

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210316_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=3000, validators=[webapp.validators.ForbiddenWordsValidator(['наркотики', 'насилие', 'алкоголь', 'терроризм'])], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=130, validators=[webapp.validators.SymbolCheckValidator(['%', '$', '@', '#', '^', '&'])], verbose_name='Название'),
        ),
    ]
