# Generated by Django 3.1.7 on 2021-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20210317_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(verbose_name='Дата начала')),
                ('finished_at', models.DateField(blank=True, null=True, verbose_name='Дата окончения')),
                ('summary', models.CharField(max_length=130, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
        ),
    ]
