# Generated by Django 3.1.7 on 2021-04-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='todolist.project', verbose_name='Из проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
