# Generated by Django 3.1.7 on 2021-04-13 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0012_auto_20210401_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
