# Generated by Django 3.1.7 on 2021-04-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('сan_update_project_user', 'Can add Project User')]},
        ),
    ]
