# Generated by Django 3.1.7 on 2021-04-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210414_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('сan_update_project_user', 'Can update Project User')]},
        ),
    ]
