# Generated by Django 3.1.7 on 2021-04-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20210414_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_project_user', 'Can update Project User')]},
        ),
    ]
