# Generated by Django 3.1.7 on 2021-04-19 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0016_auto_20210414_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_project_user', 'Can update Project User'), ('can_view_user_list', 'Can view user list')]},
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
