# Generated by Django 3.1.7 on 2021-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_auto_20210419_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_update_project_user', 'Can update Project User')]},
        ),
    ]
